#!/usr/bin/env python3
"""
Simple test of the upload material logic without LangChain tools.
"""

import json
import sys
from pathlib import Path

# Add paths for imports
sys.path.append(str(Path(__file__).parent))
sys.path.append(str(Path(__file__).parent / "ocr_module"))

def test_upload_material_logic():
    """Test the core logic of upload_material without LangChain tool wrapper."""
    try:
        from ocr_module.classroom_uploader import OCRClassroomUploader
        
        # Test chatbot format data (raw lesson plan)
        chatbot_data = {
            "title": "Python Programming Basics",
            "subject": "Computer Science",
            "grade_level": "Grade 10", 
            "duration": "60 minutes",
            "learning_objectives": ["Understand variables", "Write simple programs"],
            "key_topics": ["Variables", "Data types", "Basic syntax"],
            "lesson_structure": {
                "introduction": "What is programming?",
                "main_activities": ["Code examples", "Hands-on practice"],
                "assessment": "Simple coding exercise",
                "conclusion": "Review key concepts"
            },
            "materials_needed": ["Computer", "Python IDE"],
            "vocabulary": ["Variable", "Function", "Loop"],
            "homework_assignments": ["Practice exercises"],
            "difficulty_level": "beginner"
        }
        
        material_data_json = json.dumps(chatbot_data)
        
        # Simulate the upload_material logic
        material_info = json.loads(material_data_json)
        
        # Check if this is already in OCR format or needs to be wrapped
        if "structured_data" not in material_info:
            # This is a raw lesson plan from chatbot, wrap it in OCR format
            ocr_formatted_data = {
                "structured_data": material_info,
                "confidence_score": 0.95,
                "extraction_type": "educational_content",
                "raw_response": "Generated by chatbot",
                "errors": []
            }
        else:
            # Already in OCR format
            ocr_formatted_data = material_info
        
        # Test the conversion
        uploader = OCRClassroomUploader()
        assignment_data = uploader.convert_ocr_to_assignment(ocr_formatted_data, "material")
        
        print("✓ Chatbot lesson plan conversion successful!")
        print(f"Title: {assignment_data['title']}")
        print(f"Description length: {len(assignment_data['description'])} characters")
        print(f"Work type: {assignment_data['workType']}")
        
        # Check for comprehensive content
        description = assignment_data['description']
        expected_sections = [
            "Learning Objectives", "Key Topics", "Lesson Structure", 
            "Materials Needed", "Key Vocabulary"
        ]
        
        sections_found = sum(1 for section in expected_sections if section in description)
        print(f"Content sections found: {sections_found}/{len(expected_sections)}")
        
        if sections_found >= 4 and len(description) > 300:
            print("🎉 Comprehensive lesson plan generated successfully!")
            
            # Print a sample of the description to verify content
            print("\n📝 Sample description content:")
            print("=" * 50)
            print(description[:500] + "..." if len(description) > 500 else description)
            print("=" * 50)
            
            return True
        else:
            print("❌ Lesson plan content is incomplete")
            return False
            
    except Exception as e:
        print(f"❌ Test failed: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    print("🧪 Testing chatbot upload material logic...\n")
    
    success = test_upload_material_logic()
    
    if success:
        print("\n✅ SUCCESS: Chatbot lesson plan upload fix is working!")
        print("The fix ensures that chatbot-generated lesson plans are properly")
        print("formatted and will create comprehensive classroom assignments.")
    else:
        print("\n❌ FAILED: Fix needs more work.")